Idrinth/WARAddonClient

src/main/java/de/idrinth/waraddonclient/gui/Window.java, src/main/java/de/idrinth/waraddonclient/implementation/service/FindAddonFolder.java
Added possibility of having client in another path and it saving that into config
=> Different path

src/main/java/de/idrinth/waraddonclient/gui/Window.java
including a miss on my last commit where I forgot to close the scanner
=> added small fixes from sonarlint (there are more) 

src/main/java/de/idrinth/waraddonclient/Config.java, src/main/java/de/idrinth/waraddonclient/Main.java, src/main/java/de/idrinth/waraddonclient/Utils.java, src/main/java/de/idrinth/waraddonclient/gui/Window.java, src/main/java/de/idrinth/waraddonclient/model/ActualAddon.java, src/main/java/de/idrinth/waraddonclient/service/Backup.java
Fixes #
Fixed sonar issues
- Removed unused imports
- Changed backup from YYYY to yyyy as YYYY is week year and probably not what you want
- Changed writestringtofile to a non deprecated function
=> fix various sonar issues

.github/ISSUE_TEMPLATE/bug-report.md
- updated issue template to ask for OS
=> updated issue template to ask for OS

src/main/java/de/idrinth/waraddonclient/Main.java, src/main/java/de/idrinth/waraddonclient/model/AddonList.java
- Added option for "--updateonly" to only update all addons from commandline.
Sorry for the second PR, did not think Id get it so I trashed the first PR. Double check that this works but it seems to work on linux
=> 20210513 updateonly

src/main/java/de/idrinth/waraddonclient/Main.java, src/main/java/de/idrinth/waraddonclient/gui/TextCategory.java, src/main/java/de/idrinth/waraddonclient/gui/Window.java, src/main/java/de/idrinth/waraddonclient/model/AddonList.java, src/main/java/de/idrinth/waraddonclient/model/CmdAddonList.java, src/main/java/de/idrinth/waraddonclient/model/GuiAddonList.java, src/main/java/de/idrinth/waraddonclient/service/FileWatcher.java
- separate the code between the different versions of the client
=> split addon code between gui and cli

src/main/java/de/idrinth/waraddonclient/Main.java
- Added option to set RoR location from commandline with --setlocation "path/to/ror"
=> added option to set ROR loc from cmdline

src/main/java/de/idrinth/waraddonclient/Main.java, src/main/java/de/idrinth/waraddonclient/service/FileSystem.java
Fixes
Issues with commandline where GUI would be shown
=> fix bug in commandline

.gitmodules, pom.xml, src/main/resources/linux/WARAddonClient.desktop
- use git submodule for wrapper and set the right directory for the installed RPM
=> fix for the RPM builds

pom.xml
- Have default-build always run and not get replaced if another profile is stated on command line
=> make it so that default-build is always run and not replaced

pom.xml
- Me and Xpander had to change the structure of the other git for AUR submission.
=> addressed the path change in xpander repo

src/main/java/de/idrinth/waraddonclient/Main.java, src/main/java/de/idrinth/waraddonclient/model/CmdAddonList.java
- added command "--install {addonName}" to install addons from commandline
- added command "--remove {addonName}" to uninstall addons from commandline
=> added cmdline options to install and remove addons

pom.xml, src/main/java/de/idrinth/waraddonclient/Config.java, src/main/java/de/idrinth/waraddonclient/Main.java, src/main/resources/linux/preinst
- put logs in /tmp on linux systems to avoid the cardinal sin of placing things in the users home folder.
=> changed location for logs in linux

pom.xml
- add the dep in the pom so that it can compile
=> fix pom so that we can compile

src/main/java/de/idrinth/waraddonclient/CliMain.java
- changed --updateonly to --update-only
- changed --setlocation to --set-location
=> more linux standard. Should have been this from start

src/main/java/de/idrinth/waraddonclient/CliMain.java, src/main/java/de/idrinth/waraddonclient/model/CmdAddonList.java
- Added output when installing addon and none found in cmdline
- Added output when removing addon and none found in cmdline
- Removed output when setting war-path to follow normal linux standard where everything is fine if no output was done. (edit this out if you dont agree but I personally think we should follow linux standard)
=> cmdline output

src/main/java/de/idrinth/waraddonclient/BaseMain.java, src/main/java/de/idrinth/waraddonclient/CliMain.java, src/main/java/de/idrinth/waraddonclient/GuiMain.java, src/main/java/de/idrinth/waraddonclient/Main.java, src/main/java/de/idrinth/waraddonclient/Utils.java, src/main/java/de/idrinth/waraddonclient/cli/AliasOption.java, src/main/java/de/idrinth/waraddonclient/cli/AliasParser.java, src/main/java/de/idrinth/waraddonclient/cli/AliasedOption.java, src/main/java/de/idrinth/waraddonclient/gui/ThemeManager.java, src/main/java/de/idrinth/waraddonclient/gui/Window.java, src/main/java/de/idrinth/waraddonclient/model/ActualAddon.java, src/main/java/de/idrinth/waraddonclient/model/AddonList.java, src/main/java/de/idrinth/waraddonclient/model/CmdAddonList.java, src/main/java/de/idrinth/waraddonclient/model/GuiAddonList.java, src/main/java/de/idrinth/waraddonclient/model/TrustManager.java, src/main/java/de/idrinth/waraddonclient/service/BaseLogger.java, src/main/java/de/idrinth/waraddonclient/service/CliLogger.java, src/main/java/de/idrinth/waraddonclient/service/FileLogger.java, src/main/java/de/idrinth/waraddonclient/service/FileWatcher.java, src/main/java/de/idrinth/waraddonclient/service/GuiLogger.java, src/main/java/de/idrinth/waraddonclient/service/MultiLogger.java, src/main/java/de/idrinth/waraddonclient/service/Request.java, src/main/java/de/idrinth/waraddonclient/service/Version.java
- handle aliases by subclassing
- handle logging centrally
@Natherul would love a review
=> properly splitting aliases from normal options

src/main/java/de/idrinth/waraddonclient/gui/Window.java, src/main/java/de/idrinth/waraddonclient/model/ActualAddon.java
- save the folders that the addon installs to
- remove folders from the config file on unistall
@Natherul would love feedback
=> better uninstall

src/main/java/de/idrinth/waraddonclient/model/AddonList.java, src/main/java/de/idrinth/waraddonclient/service/Request.java
- check is subfile in addons is folder
- dont throw error from github
=> fixes for not folders in addons and not weird error on github

src/main/java/de/idrinth/waraddonclient/Main.java, src/main/java/de/idrinth/waraddonclient/model/AddonList.java, src/main/java/de/idrinth/waraddonclient/service/Config.java
- Removed unused imports
- Fixed name for userpref and if its doing it for the first time then it will extract old userpref info
=> fixed name for userpref (and get old userpref) and removed unused imports

src/main/java/de/idrinth/waraddonclient/Utils.java, src/main/java/de/idrinth/waraddonclient/cli/AliasParser.java, src/main/java/de/idrinth/waraddonclient/gui/TextCategory.java, src/main/java/de/idrinth/waraddonclient/model/GuiAddonList.java, src/main/java/de/idrinth/waraddonclient/model/Tag.java, src/main/java/de/idrinth/waraddonclient/model/TrustManager.java, src/main/java/de/idrinth/waraddonclient/model/addon/ActualAddon.java, src/main/java/de/idrinth/waraddonclient/service/Backup.java, src/main/java/de/idrinth/waraddonclient/service/Config.java, src/main/java/de/idrinth/waraddonclient/service/FileSystem.java, src/main/java/de/idrinth/waraddonclient/service/FileWatcher.java, src/main/java/de/idrinth/waraddonclient/service/Request.java
- Fixed numerous sonar issues.
- Changed load from previous userpref to load from the new as it already has a default as there was otherwise a chance that it would constantly reset your settings.
=> fixed multiple sonar issues

src/main/java/de/idrinth/waraddonclient/CliMain.java
- Added option for backup from commandline
- Added option for restore backup from commandline
=> added command options for restore and backup

.gitignore
Fixes #
- Add .idea directory to gitignore to prevent tracking of intelij configuration files
=> Update .gitignore for intelij config

src/main/java/de/idrinth/waraddonclient/model/CaseInsensitiveHashMap.java, src/main/java/de/idrinth/waraddonclient/model/TrustManager.java, src/main/java/de/idrinth/waraddonclient/model/addon/ActualAddon.java, src/main/java/de/idrinth/waraddonclient/model/addon/Addon.java, src/main/java/de/idrinth/waraddonclient/model/addon/NoAddon.java, src/main/java/de/idrinth/waraddonclient/model/addon/UnknownAddon.java, src/main/java/de/idrinth/waraddonclient/service/FileWatcher.java, src/main/java/de/idrinth/waraddonclient/service/SilencingErrorHandler.java
Addresses some easily fixed issues.  There are a few more commits for the Window class that I excluded when I realized that appears to be auto generated. I can open a pull request for those if you'd like.
Let me know if there are any concerns, commits I should exclude, or changes I may make.
- Remove unnecessary throws in method signatures
- Remove redundant interface access modifier
- Remove redundant final modifier
- Add final modifier to field
- Remove raw usage of parameterized class
=> Clean up/21.31.5/bryman

README.md
=> typo fix ;)

src/main/java/darrylbu/util/MenuScroller.java, src/main/java/de/idrinth/waraddonclient/gui/Addons.java, src/main/java/de/idrinth/waraddonclient/gui/Backups.java, src/main/java/de/idrinth/waraddonclient/gui/BaseFrame.java, src/main/java/de/idrinth/waraddonclient/gui/Start.java, src/main/java/de/idrinth/waraddonclient/model/CmdAddonList.java, src/main/java/de/idrinth/waraddonclient/model/addon/ActualAddon.java, src/main/java/de/idrinth/waraddonclient/service/Backup.java
- Changed a fair bit to lessen issues reported by sonar, please double check that everything works in this for you before accepting.
=> fixes for numerous sonar issues
